In [1]:
#Imort useful libs
import pandas as pd
import  numpy as np
import pgeocode
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
#Loaded the dataset for the training
df = pd.read_csv('house_sales.csv')

In [3]:
#DATA  PREPROCESSING
print('data shape')
print(df.shape)
print('data information')
print(df.info())
print('data head')
df.head(20)

data shape
(22687, 22)
data information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22687 entries, 0 to 22686
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DocumentDate     22687 non-null  object
 1   SalePrice        22687 non-null  int64
 2   PropertyID       22687 non-null  int64
 3   PropertyType     22687 non-null  object
 4   ym               22687 non-null  object
 5   zhvi_px          22687 non-null  int64
 6   zhvi_idx         22687 non-null  float64
 7   AdjSalePrice     22687 non-null  float64
 8   NbrLivingUnits   22687 non-null  int64
 9   SqFtLot          22687 non-null  int64
 10  SqFtTotLiving    22687 non-null  int64
 11  SqFtFinBasement  22687 non-null  int64
 12  Bathrooms        22687 non-null  float64
 13  Bedrooms         22687 non-null  int64
 14  BldgGrade        22687 non-null  int64
 15  YrBuilt          22687 non-null  int64
 16  YrRenovated      22687 non-null  int64
 17  TrafficNoise     22687 non-null  int64
 18  LandVal          22687 non-null  int64
 19  ImpsVal          22687 non-null  int64
 20  ZipCode          22687 non-null  int64
 21  NewConstruction  22687 non-null  bool
dtypes: bool(1), float64(3), int64(15), object(3)
memory usage: 3.7+ MB
None
data head

,DocumentDate,SalePrice,PropertyID,PropertyType,ym,zhvi_px,zhvi_idx,AdjSalePrice,NbrLivingUnits,SqFtLot,...,Bathrooms,Bedrooms,BldgGrade,YrBuilt,YrRenovated,TrafficNoise,LandVal,ImpsVal,ZipCode,NewConstruction
0,2014-09-16,280000,1000102,Multiplex,2014-09-01,405100,0.930836,300805.0,2,9373,...,3.00,6,7,1991,0,0,70000,229000,98002,False
1,2006-06-16,1000000,1200013,Single Family,2006-06-01,404400,0.929228,1076162.0,1,20156,...,3.75,4,10,2005,0,0,203000,590000,98166,True
2,2007-01-29,745000,1200019,Single Family,2007-01-01,425600,0.977941,761805.0,1,26036,...,1.75,4,8,1947,0,0,183000,275000,98166,False
3,2008-02-25,425000,2800016,Single Family,2008-02-01,418400,0.961397,442065.0,1,8618,...,3.75,5,7,1966,0,0,104000,229000,98168,False
4,2013-03-29,240000,2800024,Single Family,2013-03-01,351600,0.807904,297065.0,1,8620,...,1.75,4,7,1948,0,0,104000,205000,98168,False
5,2009-03-30,349900,3600090,Townhouse,2009-03-01,369800,0.849724,411781.0,1,1012,...,1.50,2,8,2008,0,0,170000,207000,98144,True
6,2013-08-28,327500,3800004,Single Family,2013-08-01,374300,0.860064,380785.0,1,34465,...,1.50,3,8,1961,0,0,165000,227000,98178,False
7,2007-05-24,347000,3800009,Single Family,2007-05-01,432100,0.992877,349489.0,1,14659,...,1.75,4,7,1963,0,0,115000,154000,98178,False
8,2006-09-22,220400,6600055,Single Family,2006-09-01,414800,0.953125,231239.0,1,5324,...,1.00,2,6,1930,0,3,90000,75000,98032,False
9,2006-08-22,437500,7200080,Multiplex,2006-08-01,411100,0.944623,463148.0,2,10585,...,2.00,4,6,1924,0,0,124000,116000,98055,False
10,2014-10-16,150000,7200179,Single Family,2014-10-01,407400,0.936121,160236.0,1,12750,...,1.00,2,6,1925,0,0,133000,73000,98055,False
11,2010-01-14,300000,7400054,Single Family,2010-01-01,350800,0.806066,372178.0,1,5200,...,1.00,3,7,1958,0,1,100000,172000,98118,False
12,2008-06-26,292000,7400062,Single Family,2008-06-01,403200,0.926471,315175.0,1,5240,...,1.00,2,6,1925,0,1,100000,152000,98118,False
13,2014-05-21,299800,7400062,Single Family,2014-05-01,398100,0.914752,327739.0,1,5240,...,1.00,2,6,1925,0,1,100000,152000,98118,False
14,2006-09-25,605000,7600093,Single Family,2006-09-01,414800,0.953125,634754.0,1,7320,...,2.75,3,8,1901,0,0,261000,422000,98122,False
15,2007-02-24,425000,7600203,Single Family,2007-02-01,427800,0.982996,432352.0,1,3485,...,1.50,4,7,1920,0,0,235000,373000,98122,False
16,2006-03-14,455000,9000210,Single Family,2006-03-01,392100,0.900965,505014.0,1,5253,...,1.75,3,6,1919,0,0,333000,117000,98115,False
17,2007-11-09,495000,10000060,Single Family,2007-11-01,428400,0.984375,502857.0,1,4600,...,2.25,3,7,1909,0,0,212000,366000,98116,False
18,2013-06-05,279500,11000040,Single Family,2013-06-01,366100,0.841222,332255.0,1,27229,...,3.00,3,6,2000,0,0,142000,189000,98001,False
19,2008-03-20,400000,11000041,Single Family,2008-03-01,415100,0.953814,419369.0,1,24034,...,2.00,4,8,1960,0,0,139000,200000,98001,False

In [4]:
#Data pre processing continues
print('duplicates')
print(df.duplicated().sum())
print('null values')
print(df.isnull().sum())
print('List of columns')
df.columns

duplicates
0
null values
DocumentDate       0
SalePrice          0
PropertyID         0
PropertyType       0
ym                 0
zhvi_px            0
zhvi_idx           0
AdjSalePrice       0
NbrLivingUnits     0
SqFtLot            0
SqFtTotLiving      0
SqFtFinBasement    0
Bathrooms          0
Bedrooms           0
BldgGrade          0
YrBuilt            0
YrRenovated        0
TrafficNoise       0
LandVal            0
ImpsVal            0
ZipCode            0
NewConstruction    0
dtype: int64
List of columns

Index(['DocumentDate', 'SalePrice', 'PropertyID', 'PropertyType', 'ym',
       'zhvi_px', 'zhvi_idx', 'AdjSalePrice', 'NbrLivingUnits', 'SqFtLot',
       'SqFtTotLiving', 'SqFtFinBasement', 'Bathrooms', 'Bedrooms',
       'BldgGrade', 'YrBuilt', 'YrRenovated', 'TrafficNoise', 'LandVal',
       'ImpsVal', 'ZipCode', 'NewConstruction'],
      dtype='object')

In [5]:
#Dropping some unuseful cols in the dataset
df.drop(['DocumentDate','PropertyID','ym','zhvi_px','zhvi_idx','AdjSalePrice','YrRenovated','LandVal','ImpsVal'],axis=1,inplace=True)

In [6]:
df.shape
df.columns
df.head()

,SalePrice,PropertyType,NbrLivingUnits,SqFtLot,SqFtTotLiving,SqFtFinBasement,Bathrooms,Bedrooms,BldgGrade,YrBuilt,TrafficNoise,ZipCode,NewConstruction
0,280000,Multiplex,2,9373,2400,0,3.00,6,7,1991,0,98002,False
1,1000000,Single Family,1,20156,3764,1452,3.75,4,10,2005,0,98166,True
2,745000,Single Family,1,26036,2060,900,1.75,4,8,1947,0,98166,False
3,425000,Single Family,1,8618,3200,1640,3.75,5,7,1966,0,98168,False
4,240000,Single Family,1,8620,1720,0,1.75,4,7,1948,0,98168,False

In [6]:
#Used geocode to get the location like city and state for the houses using their zip code for model  optimisation
man = pgeocode.Nominatim('us')
df['ZipCode'] = df['ZipCode'].astype(str).str.zfill(5)
uni_zip =   df['ZipCode'].unique()
zip_city = {z:man.query_postal_code(z)['place_name'] for z in uni_zip}
zip_state = {z:man.query_postal_code(z)[
    'state_name'] for z in uni_zip}
#Now locating and choosing the city and state for the houses
df['city'] = df['ZipCode'].map(zip_city)
df['state'] = df['ZipCode'].map(zip_state)

In [7]:
#Now for  my recommendation and stream lit model I need the main dataset as it iss before encoding or scaling so that i can use them in recommending real house for  user to see features they understand
import os
import joblib
os.makedirs('Jaypee', exist_ok=True)
df.to_csv('original_data.csv', index=False)

In [ ]:
print(df['state'].unique()) #Check if states are unique

In [ ]:
#Deopped the state column as all the house are in same state
df.drop(['ZipCode','state'],axis=1,  inplace = True)
original_cats = df[['PropertyType', 'city', 'NewConstruction']].copy()

In [ ]:
from sklearn.preprocessing import  OrdinalEncoder, StandardScaler
#Performed encoding and scaling before training
cols = ['city','PropertyType']
enc = OrdinalEncoder()
df[cols] = enc.fit_transform(df[cols])
df['NewConstruction'] = df['NewConstruction'].astype(int)
sle = StandardScaler()
scale_cols = ['SqFtLot', 'SqFtTotLiving', 'SqFtFinBasement']
df[scale_cols] = sle.fit_transform(df[scale_cols])

In [ ]:
from sklearn.model_selection import train_test_split
#Selecting the train and test datsets
X= df.drop('SalePrice', axis=1)
y = df['SalePrice']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

In [ ]:
print(df.shape)
print(df.head())

In [ ]:
from xgboost import XGBRegressor
#Drfined the model and some of the unique components i choose
house_model =  XGBRegressor(
    learning_rate=0.01,
    n_estimators=1200,
    objective='reg:squarederror',
    min_child_weight=4,
    colsample_bytree=0.7,
    subsample=0.8,
    max_depth=7,
    reg_alpha=0,
    reg_lambda=1,
    n_jobs=-1,
    random_state=42,
)
house_model.fit(X_train, y_train)

In [ ]:
from sklearn.metrics  import mean_squared_error, r2_score, mean_absolute_error,root_mean_squared_error
#Evaluated the accuracy of the model using some metrics
y_pred = house_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print('mean squared error')
print(mse)
print('r2 score')
print(r2)
print('mean absolute error')
print(mae)
print('root mean square error')
print(rmse)

from sklearn.model_selection import RandomizedSearchCV
parameters = {
    'learning_rate': [0.01, 0.03, 0.05, 0.1],
    'max_depth': [4, 5, 6, 7, 8, 10],
    'min_child_weight': [1, 2, 3, 4, 5],
    'subsample': [0.6, 0.7, 0.8, 0.9],
    'colsample_bytree': [0.6, 0.7, 0.8, 0.9],
    'gamma': [0, 0.1, 0.2, 0.3, 0.5],
    'n_estimators': [600, 800, 1000, 1200]
}
model2 = XGBRegressor(
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1
)
search = RandomizedSearchCV(
    estimator=model2,
    param_distributions=parameters,
    random_state=42,
    n_iter=30,
    scoring='neg_root_mean_squared_error',
     cv=3,
    verbose=2,
)
#search.fit(X_train, y_train)
#print('Best parameters')
#print(search.best_params_)

#Best_model =  (search.best_estimator_)
#y_pred2= Best_model.predict(X_test)
#mse2 = mean_squared_error(y_test, y_pred2)
r22 = r2_score(y_test, y_pred2)
mae2 = mean_absolute_error(y_test, y_pred2)
rmse2 = root_mean_squared_error(y_test, y_pred2)

#print('mae2')
#print(mae2)
#print('rmse2')
#print(rmse2)
#print('mse2')
#print(mse2)
#print('r22')
#print(r22)

In [ ]:
#Compared some  of the predicted to the actual values
compared_df = X_test.copy()
compared_df['Actual_price'] = y_test
compared_df['Predicted_price'] = y_pred
compared_df[['PropertyType', 'city', 'NewConstruction']] = original_cats.loc[X_test.index, ['PropertyType', 'city', 'NewConstruction']]
print(compared_df.shape)
compared_df.head()

In [ ]:
import matplotlib.pyplot as plt
# A plot imporatnce showing most important features for prediction
from xgboost import plot_importance
plot_importance(house_model,
            importance_type='gain',
            max_num_features=12,
            height= 0.8,
            color='skyblue',
)
plt.title(' features importance for the predictive model')
plt.show()

In [ ]:
#Saved some of the functions and  the modeel so that i can deploy them later rusing s streamlit app
joblib.dump(house_model, 'C:/Users/CHIDOZIE/PycharmProjects/Capstone projects/House app/house_model.pkl')
joblib.dump(enc, 'C:/Users/CHIDOZIE/PycharmProjects/Capstone projects/House app/ordinary_encoder_house_model.pkl')
joblib.dump(sle,'C:/Users/CHIDOZIE/PycharmProjects/Capstone projects/House app/scaler_house_model.pkl')
joblib.dump(X_train, 'C:/Users/CHIDOZIE/PycharmProjects/Capstone projects/House app/X_train.pkl')
joblib.dump(df[['SalePrice','city','PropertyType','BldgGrade','YrBuilt','SqFtLot','SqFtTotLiving','SqFtFinBasement'	]], 'C:/Users/CHIDOZIE/PycharmProjects/Capstone projects/House app/original2.pkl')

In [ ]:
print(df['SqFtFinBasement'].min())

In [ ]:
print('hello World ')
if 1+4 == 6:
    print('Omo')
else:
    print('God is in charge')